# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Professional\PycharmProjects\Old_Anna\Nastya_diplom\Main_logining.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Logining(object):
    def setupUi(self, Logining):
        Logining.setObjectName("Logining")
        Logining.resize(213, 197)
        Logining.setStyleSheet("  QMainWindow {\n"
"       background-color: #5effec; /* Замените на нужный вам цвет */\n"
"       color: black; /* Цвет текста */\n"
"   }")
        self.centralwidget = QtWidgets.QWidget(Logining)
        self.centralwidget.setObjectName("centralwidget")
        self.label_error = QtWidgets.QLabel(self.centralwidget)
        self.label_error.setGeometry(QtCore.QRect(10, 90, 191, 31))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_error.setFont(font)
        self.label_error.setStyleSheet("  QLable {\n"
"       color:  red; /* Цвет текста */\n"
"  }")
        self.label_error.setText("")
        self.label_error.setObjectName("label_error")
        self.Password = QtWidgets.QLineEdit(self.centralwidget)
        self.Password.setGeometry(QtCore.QRect(50, 60, 113, 31))
        self.Password.setStyleSheet("  QLineEdit {\n"
"       border-radius: 10px; /* Замените на нужное значение */\n"
"       border: 1px solid #c4faff; /* Цвет и стиль границы */\n"
"       background-color: #c4faff; /* Замените на нужный вам цвет */\n"
"       color: black; /* Цвет текста */\n"
"       padding: 5px; /* Внутренние отступы */\n"
"   }")
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password.setObjectName("Password")
        self.Login = QtWidgets.QLineEdit(self.centralwidget)
        self.Login.setGeometry(QtCore.QRect(50, 20, 113, 31))
        self.Login.setStyleSheet("  QLineEdit {\n"
"       border-radius: 10px; /* Замените на нужное значение */\n"
"       border: 1px solid #c4faff; /* Цвет и стиль границы */\n"
"       background-color: #c4faff; /* Замените на нужный вам цвет */\n"
"       color: black; /* Цвет текста */\n"
"       padding: 5px; /* Внутренние отступы */\n"
"   }")
        self.Login.setObjectName("Login")
        self.But_entr = QtWidgets.QPushButton(self.centralwidget)
        self.But_entr.setGeometry(QtCore.QRect(70, 120, 75, 31))
        self.But_entr.setStyleSheet("  QPushButton {\n"
"       border-radius: 10px; \n"
"       border: 1px solid #c4faff; /* Цвет и стиль границы */\n"
"       background-color: #11e9ff; /* Замените на нужный вам цвет */\n"
"       color: black; /* Цвет текста */\n"
"       padding: 5px; /* Внутренние отступы */\n"
"   }")
        self.But_entr.setObjectName("But_entr")
        Logining.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Logining)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 213, 21))
        self.menubar.setObjectName("menubar")
        Logining.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Logining)
        self.statusbar.setObjectName("statusbar")
        Logining.setStatusBar(self.statusbar)

        self.retranslateUi(Logining)
        QtCore.QMetaObject.connectSlotsByName(Logining)

    def retranslateUi(self, Logining):
        _translate = QtCore.QCoreApplication.translate
        Logining.setWindowTitle(_translate("Logining", "MainWindow"))
        self.But_entr.setText(_translate("Logining", "Вход"))
